Server:
  Mode: release # debug | release
  Port: :8765
  DbType: "mysql" # mysql | sqlite
  DbAutoMigrate: true # 是否自动迁移数据库表结构 (表结构没变可以不迁移, 提高启动速度)
JWT:
  Secret: "abc123321"
  Expire: 7 #  过期时间, 单位天
  Issuer: "akita"
Mysql:
  Host: "114.55.131.151"
  Port: "3306"
  Config: "charset=utf8mb4&parseTime=True&loc=Local" # 其他配置, 例如时区
  Dbname: "ginvueblog"
  Username: "root"
  Password: "qiutianhong"
  LogMode: "error" # 日志级别 silent, error, warn, info, 默认 info
Sqlite:
  Dsn: "gvb.db"
Redis:
  DB: 7
  Addr: '114.55.131.151:6379'
  Password: ''
Session:
  Name: "mysession"
  Salt: "salt"
  MaxAge: 600 # second
Log:
  Level: "error" # debug | info | warn | error
  Format: "text" # text | json
  Directory: "log"
Email:
  Host: "smtp.qq.com" # 服务器地址, 例如 smtp.qq.com 前往要发邮件的邮箱查看其 smtp 协议
  Port: 587 # 前往要发邮件的邮箱查看其 smtp 协议端口, 大多为 465
  From: "<1240092443@qq.com>" # 发件人 (邮箱)
  IsSSL: true # 是否开启 SSL
  Secret: "jylufwtdclmcbaaa" # 密钥, 不是邮箱登录密码, 是开启 smtp 服务后获取的一串验证码
  Nickname: "124009244" # 发件人昵称, 通常为自己的邮箱名
Captcha:
  SendEmail: true # 通过邮箱发送验证码
  ExpireTime: 15  # 过期时间 (分钟)
Upload:
  OssType: "local" # local | qiniu
  Path: "public/uploaded"      # 本地文件访问路径 (OssType="local" 才生效)
  StorePath: "public/uploaded" # 本地文件上传路径 (OssType="local" 才生效)
Qiniu:
  ImgPath: "cdn.akita324.top" # 外链
  Zone: "z2"
  Bucket: "akitablog"
  AccessKey: "rsabvDKcxGOzeXbtR-8dF9GnUijb10BQrBuo7m5X"
  SecretKey: "PnVkBEZwrgYG82r4NDx3lWgRF621bluJ7mfxUA5b"
  UseHttps: false
  UseCdnDomains: false